[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self' 'unsafe-inline' https://www.googletagmanager.com https://ssl.google-analytics.com https://www.google-analytics.com https://pl16160949.profitabletrustednetwork.com"
    connectSrc = "*"
    styleSrc = "'self' 'unsafe-inline' https://fonts.googleapis.com"
    baseUri = "'self'"
    formAction = "'self'"
    manifestSrc = "'self'"
    imgSrc = "* data:"
    frameSrc = "https://utteranc.es"
    fontSrc = "https://fonts.gstatic.com"
    workerSrc = "'self'"