name: Smoke tests

on:
  status

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: -v /dev/shm:/dev/shm
        
    steps:
    - name: Create smoke tests QUEUED status commit comment
      if: ${{ github.event.state == 'pending' }}
      uses: peter-evans/commit-comment@v1
      with:
        sha: ${{ github.event.commit.sha }}
        body: Preview deploy started, waiting for completion to start the smoke tests...
    - name: Create smoke tests STARTED status commit comment
      if: ${{ github.event.state == 'success' }}
      uses: peter-evans/commit-comment@v1
      with:
        sha: ${{ github.event.commit.sha }}
        body: Preview deploy ended, starting smoke tests...
    - run: echo ::set-env name=SITE_URL::${{ github.github.event.target_url }}
      if: ${{ github.event.state == 'success' }}
    - uses: actions/checkout@v2
      if: ${{ github.event.state == 'success' }}
      with:
        ref: ${{ github.event.commit.sha }}
    - name: Use Node.js 10.x
      if: ${{ github.event.state == 'success' }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g yarn
      if: ${{ github.event.state == 'success' }}
    - run: yarn install
      if: ${{ github.event.state == 'success' }}
    - run: yarn test-ci
      if: ${{ github.event.state == 'success' }}
    - name: Create smoke tests FINISHED status commit comment
      if: ${{ github.event.state == 'success' }}
      uses: peter-evans/commit-comment@v1
      with:
        sha: ${{ github.event.commit.sha }}
        body: Smoke tests ended with status ${{ job.status }}