name: Smoke tests

on:
  status

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: -v /dev/shm:/dev/shm
        
    steps:
    - name: Create smoke tests PENDING status commit comment
      if: ${{ github.event.state == 'pending' }}
      run: |
        curl --location --request POST
        'https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.commit.sha }}'
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
        --header 'Content-Type: application/json'
        --data-raw '{
        "state": "pending",
        "target_url": "https://github.com/${{ github.repository }}/actions?query=workflow%253A%22${{ github.workflow }}",
        "context": "${{ github.workflow }}",
        "descrption": "Waiting for deployment"
        }'
    - name: Extract deployment URL
      run: echo ::set-env name=SITE_URL::${{ github.github.event.target_url }}
      if: ${{ github.event.state == 'success' }}
    - name: Checkout
      uses: actions/checkout@v2
      if: ${{ github.event.state == 'success' }}
      with:
        ref: ${{ github.event.commit.sha }}
    - name: Use Node.js 10.x
      if: ${{ github.event.state == 'success' }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install -g yarn
      if: ${{ github.event.state == 'success' }}
    - run: yarn install
      if: ${{ github.event.state == 'success' }}
    - run: yarn test-ci
      if: ${{ github.event.state == 'success' }}
    - name: Create smoke tests FINISHED status commit comment
      if: ${{ github.event.state == 'success' }}
      run: |
        curl --location --request POST
        'https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.commit.sha }}'
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
        --header 'Content-Type: application/json'
        --data-raw '{
        "state": "${{ job.status }}",
        "target_url": "https://github.com/t3rmian/devpot/actions?query=workflow%253A%22${{ github.workflow }}",
        "context": "${{ github.workflow }}",
        "descrption": "Waiting for deployment"
        }'
